export const authCardText = {
  registerEyebrow: "Create an Account",
  loginEyebrow: "Sign In",
  registerHeading: "Welcome to ByteSpace",
  loginHeading: "Welcome Back",
  fullNameLabel: "Full Name",
  fullNamePlaceholder: "Jamie Davis",
  emailLabel: "Email",
  emailPlaceholder: "designer@example.com",
  passwordLabel: "Password",
  passwordPlaceholder: "••••••••",
  continueButton: "Continue",
  signInButton: "Sign In",
  facebookSignIn: "Continue with Facebook",
  googleSignIn: "Continue with Google",
  existingAccount: "Already have an account? ",
  newAccount: "New user? ",
  loginLink: "Login",
  createAccountLink: "Create an account",
};
