export const coursePageText = {
  searchTitle: "Find Your Next Course",
  searchLabel: "Search courses",
  searchPlaceholder: "Search courses",
  filterButton: "Filter",
  levelLabel: "Filter by level",
  categoryLabel: "Filter by category",
  sortLabel: "Sort courses",
  allLevels: ["All levels", "Beginner", "Intermediate", "Advanced"],
  allCategories: "All categories",
  levelPlaceholder: "Level",
  categoryPlaceholder: "Category",
  sortOptions: ["Most relevant", "Price: low to high", "Rating"],
  featuredCategory: "Featured",
  pagesLabel: "Course pages",
  previousPage: "Previous page",
  nextPage: "Next page",
  pageLabel: "Page",
};
