export const courseViewText = {
  previewAlt: "Course preview",
  creatorPrefix: "by",
  playPreviewLabel: "Play course preview",
  fallbackLessonCount: "112 Lessons",
  fallbackDuration: "24 hours",
  moreVideos: "99 more videos",
  enrollmentPrompt: "Ready to Dive In? Enroll Now and Start Building Your Digital Future!",
  lifetime: "/lifetime",
  enrollButton: "Enroll Now",
  includesHeading: "This course includes",
  includedFeatures: [
    "Learning Resources",
    "Quality Lesson Videos",
    "Certificate of Completion",
    "Private Consultation",
  ],
  creatorAlt: "Course creator",
  creatorRole: "Professional Creator",
  viewProfileButton: "See Full Profile",
  detailsNavigationLabel: "Course details",
  tabs: ["about", "lessons", "reviews"] as const,
  descriptionHeading: "Description",
  descriptionFallback: "Build practical knowledge through a clear, project-focused learning experience.",
  sneakPeekHeading: "Sneak Peek",
  sneakPeekAlt: "Course sneak peek",
  keyPointsHeading: "Key Points",
  modulesHeading: "Explore the Modules",
  modulesFallback: "Work through each module with practical lessons and guided exercises.",
  lessonListHeading: "Lesson List",
  moduleLabel: "Module",
  lessonContentHeading: "Lesson Content",
  lessonContentFallback: "Engage with video lessons, practical resources, and activities designed to reinforce your understanding.",
  progressLabel: "Lesson progress",
  reviewsHeading: "What Learners Are Saying",
  reviewsDescription: "Discover what our learners have to say about their experience with 'Build Digital Assets: A Comprehensive Guide.' Read reviews and ratings from individuals who have embarked on the transformative journey of mastering digital asset creation.",
  ratingSummaryLabel: "Ratings",
  ratingAverage: "4.7",
  reviewsListHeading: "Individual Reviews:",
  allRatingsFilter: "All rating",
  reviewRatingAlt: "stars",
  reviewStarAlt: "stars",
  ratingDistribution: [
    { rating: 5, count: 720, width: "w-3/5" },
    { rating: 4, count: 120, width: "w-1/5" },
    { rating: 3, count: 21, width: "w-1/6" },
    { rating: 2, count: 12, width: "w-1/7" },
    { rating: 1, count: 16, width: "w-1/8" },
  ],
  reviews: [
    { reviewer: 1, name: "PurePearl Studio", role: "UI/UX Designer", rating: 5, date: "a year ago", text: "The course provided me with a comprehensive understanding of digital asset creation. The lessons were in-depth, practical, and immediately applicable to my work. Highly recommended!" },
    { reviewer: 2, name: "James L.", role: "Lifelong Learner", rating: 5, date: "8 months ago", text: "The modules were clear, practical, and easy to follow. I especially enjoyed applying the design principles in the project exercises." },
    { reviewer: 3, name: "Alex B.", role: "Inspired Creator", rating: 4, date: "6 months ago", text: "A thoughtful course with useful examples and a strong final project. It gave me a much better process for building digital assets." },
    { reviewer: 4, name: "Sarah M.", role: "Enthusiastic Learner", rating: 5, date: "4 months ago", text: "The explanations were engaging and the practical lessons helped me build confidence throughout the course." },
  ],
  fallbackLessons: [
    { title: "Introduction and course overview", description: "Get familiar with the course structure and learning goals.", duration: "10 mins" },
    { title: "Understanding the essential concepts", description: "Build a strong foundation with the core ideas covered in this course.", duration: "20 mins" },
    { title: "Building your first practical project", description: "Apply your new skills in a guided, hands-on project.", duration: "30 mins" },
  ],
};
