export const courseDetails = [
    {
    id: "learn-figma-from-basic",
        imageSrc: "/course1.jpg",
        title: "Learn Figma from Basic",
        byWhom: "purepearl studio",
        rating: "4.5",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "UI/UX Design",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer3.png"],
        price: "$25",
        lessons: "24 Lessons",
        duration: "5 hours",
        comments: "59 Comments",
    },
    {
        id: "build-digital-asset",
        imageSrc: "/course2.jpg",
        title: "Build Digital Asset",
        tagline: "Unlock the Power of Digital Creation with Expert Guidance",
        byWhom: "purepearl studio",
        rating: "4.5",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Digital Illustration",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer3.png", "/buyer4.png"],
        price: "$35",
        lessons: "34 Lessons",
        duration: "5 hours",
        comments: "59 Comments",
        description: [
            "Embark on an enlightening exploration into the world of digital creation with our comprehensive course, \"Build Digital Assets: A Comprehensive Guide.\" This transformative learning experience invites you to delve deep into the intricacies of crafting impactful digital content. From laying the groundwork with foundational concepts to mastering advanced techniques, this guide is meticulously curated to empower you with the skills essential for navigating the dynamic landscape of digital asset creation.",
            "In the initial modules, you'll establish a solid foundation by immersing yourself in the foundational concepts that form the backbone of digital asset creation. Understand the fundamental elements that constitute compelling digital content and gain proficiency in leveraging these elements to communicate effectively in the digital realm.",
            "As you progress through the course, you'll ascend to higher levels of expertise, delving into the nuances of design principles that drive impactful creations. Uncover the secrets behind effective visual communication, exploring color theory, typography, and layout strategies that elevate your digital assets to new heights. Engage in hands-on exercises that reinforce your understanding, allowing you to apply these principles in practical scenarios.",
        ],
        keyPoints: [
            "Foundational Concepts",
            "Design Principles Mastery",
            "Advanced Techniques in Digital Creation",
            "Project Showcase and Critique",
            "Optimizing for Various Platforms",
            "Digital Asset Management Best Practices",
            "Monetization Strategies",
            "Capstone Project: Building Your Portfolio",
        ],
        lessonOverview: "Immerse yourself in the course content as we break down each module into comprehensive lessons, providing practical insights and hands-on experiences.",
        lessonContent: "Engage with each lesson through captivating video content, detailed textual explanations, and interactive elements. Download resources, complete assignments, and test your understanding with quizzes.",
        lessonProgress: 55,
        lessonModules: [
            { title: "Introduction to Digital Assets", description: "Lay the groundwork with lessons like Understanding Digital Elements and Navigating Design Software Tools.", duration: "12 mins" },
            { title: "Design Principles Mastery", description: "Master the principles that drive impactful designs with lessons such as Color Theory in Digital Design and Typography Essentials.", duration: "21 mins" },
            { title: "Advanced Techniques in Digital Creation", description: "Explore advanced techniques and elevate your digital creations with practical exercises.", duration: "26 mins" },
            { title: "User-Centric Design Strategies", description: "Understand user experience and interaction design through research, testing, and real-world examples.", duration: "24 mins" },
            { title: "Interactive Media and Engagement", description: "Engage your audience with interactive presentations and multimedia experiences.", duration: "18 mins" },
            { title: "Project Showcase and Critique", description: "Perfect your presentation skills and embrace collaboration with peer critique and feedback.", duration: "22 mins" },
            { title: "Optimizing Digital Assets for Various Platforms", description: "Adapt your digital creations for mobile platforms and social media across devices.", duration: "20 mins" },
        ],
    },
    {
        id: "power-of-big-data",
        imageSrc: "/course3.jpg",
        title: "The Power of Big Data",
        byWhom: "purepearl studio",
        rating: "4.5",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Data Science",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer4.png"],
        price: "$45",
        lessons: "14 Lessons",
        duration: "5 hours",
        comments: "59 Comments",
    },
    {
        id: "balancing-productivity-self-care",
        imageSrc: "/course4.jpg",
        title: "Balancing Productivity and Self-Care",
        byWhom: "purepearl studio",
        rating: "4.5",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Productivity",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer4.png"],
        price: "$45",
        lessons: "14 Lessons",
        duration: "5 hours",
        comments: "59 Comments",
    },
    {
        id: "mastering-money-management",
        imageSrc: "/course5.jpg",
        title: "Mastering Money Management",
        byWhom: "purepearl studio",
        rating: "4.5",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Marketing",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer4.png"],
        price: "$45",
        lessons: "14 Lessons",
        duration: "5 hours",
        comments: "59 Comments",
    },
    {
        id: "idea-to-startup-success",
        imageSrc: "/course6.jpg",
        title: "From Idea to Startup Success",
        byWhom: "purepearl studio",
        rating: "4.5",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Creative Marketing",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer4.png"],
        price: "$45",
        lessons: "14 Lessons",
        duration: "5 hours 9 minutes",
        comments: "59 Comments",
    },

    {
        id: "idea-to-startup-success-intermediate",
        imageSrc: "/course1.jpg",
        title: "From Idea to Startup Success",
        byWhom: "purepearl studio",
        rating: "4.5",
        ratingLogo: "/star.png",
        friendly: "Intermediate",
        category: "Web Development",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer4.png"],
        price: "$45",
        lessons: "14 Lessons",
        duration: "12 hours",
        comments: "59 Comments",
    },
];