export const courseDetails = [
    {
        imageSrc: "/course1.jpg",
        title: "Learn Figma from Basic",
        byWhom: "purepearl studio",
        rating: "4.5",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "UI/UX Design",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer3.png"],
        price: "$25",
        lessons: "24 Lessons",
        duration: "5 hours",
        comments: "59 Comments",
    },
    {
        imageSrc: "/course2.jpg",
        title: "Build Digital Asset",
        byWhom: "purepearl studio",
        rating: "4.5",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Digital Illustration",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer3.png", "/buyer4.png"],
        price: "$35",
        lessons: "34 Lessons",
        duration: "5 hours",
        comments: "59 Comments",
    },
    {
        imageSrc: "/course3.jpg",
        title: "The Power of Big Data",
        byWhom: "purepearl studio",
        rating: "4.5",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Data Science",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer4.png"],
        price: "$45",
        lessons: "14 Lessons",
        duration: "5 hours",
        comments: "59 Comments",
    },
    {
        imageSrc: "/course4.jpg",
        title: "Balancing Productivity and Self-Care",
        byWhom: "purepearl studio",
        rating: "4.5",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Productivity",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer4.png"],
        price: "$45",
        lessons: "14 Lessons",
        duration: "5 hours",
        comments: "59 Comments",
    },
    {
        imageSrc: "/course5.jpg",
        title: "Mastering Money Management",
        byWhom: "purepearl studio",
        rating: "4.5",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Marketing",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer4.png"],
        price: "$45",
        lessons: "14 Lessons",
        duration: "5 hours",
        comments: "59 Comments",
    },
    {
        imageSrc: "/course6.jpg",
        title: "From Idea to Startup Success",
        byWhom: "purepearl studio",
        rating: "4.5",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Creative Marketing",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer4.png"],
        price: "$45",
        lessons: "14 Lessons",
        duration: "5 hours 9 minutes",
        comments: "59 Comments",
    },

    {
        imageSrc: "/course1.jpg",
        title: "From Idea to Startup Success",
        byWhom: "purepearl studio",
        rating: "4.5",
        ratingLogo: "/star.png",
        friendly: "Intermediate",
        category: "Web Development",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer4.png"],
        price: "$45",
        lessons: "14 Lessons",
        duration: "12 hours",
        comments: "59 Comments",
    },
];