export const courseDetails = [
    {
        id: "learn-figma-from-basic",
        imageSrc: "/course1.jpg",
        title: "Learn Figma from Basic",
        byWhom: "purepearl studio",
        rating: "4.5",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "UI/UX Design",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer3.png"],
        price: "$25",
        lessons: "24 Lessons",
        duration: "5 hours",
        comments: "59 Comments",
    },
    {
        id: "build-digital-asset",
        imageSrc: "/course2.jpg",
        title: "Build Digital Asset",
        tagline: "Unlock the Power of Digital Creation with Expert Guidance",
        byWhom: "purepearl studio",
        rating: "4.5",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Digital Illustration",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer3.png", "/buyer4.png"],
        price: "$35",
        lessons: "34 Lessons",
        duration: "5 hours",
        comments: "59 Comments",
        description: [
            "Embark on an enlightening exploration into the world of digital creation with our comprehensive course, \"Build Digital Assets: A Comprehensive Guide.\" This transformative learning experience invites you to delve deep into the intricacies of crafting impactful digital content. From laying the groundwork with foundational concepts to mastering advanced techniques, this guide is meticulously curated to empower you with the skills essential for navigating the dynamic landscape of digital asset creation.",
            "In the initial modules, you'll establish a solid foundation by immersing yourself in the foundational concepts that form the backbone of digital asset creation. Understand the fundamental elements that constitute compelling digital content and gain proficiency in leveraging these elements to communicate effectively in the digital realm.",
            "As you progress through the course, you'll ascend to higher levels of expertise, delving into the nuances of design principles that drive impactful creations. Uncover the secrets behind effective visual communication, exploring color theory, typography, and layout strategies that elevate your digital assets to new heights. Engage in hands-on exercises that reinforce your understanding, allowing you to apply these principles in practical scenarios.",
        ],
        keyPoints: [
            "Foundational Concepts",
            "Design Principles Mastery",
            "Advanced Techniques in Digital Creation",
            "Project Showcase and Critique",
            "Optimizing for Various Platforms",
            "Digital Asset Management Best Practices",
            "Monetization Strategies",
            "Capstone Project: Building Your Portfolio",
        ],
        lessonOverview: "Immerse yourself in the course content as we break down each module into comprehensive lessons, providing practical insights and hands-on experiences.",
        lessonContent: "Engage with each lesson through captivating video content, detailed textual explanations, and interactive elements. Download resources, complete assignments, and test your understanding with quizzes.",
        lessonProgress: 55,
        lessonModules: [
            { title: "Introduction to Digital Assets", description: "Lay the groundwork with lessons like Understanding Digital Elements and Navigating Design Software Tools.", duration: "12 mins" },
            { title: "Design Principles Mastery", description: "Master the principles that drive impactful designs with lessons such as Color Theory in Digital Design and Typography Essentials.", duration: "21 mins" },
            { title: "Advanced Techniques in Digital Creation", description: "Explore advanced techniques and elevate your digital creations with practical exercises.", duration: "26 mins" },
            { title: "User-Centric Design Strategies", description: "Understand user experience and interaction design through research, testing, and real-world examples.", duration: "24 mins" },
            { title: "Interactive Media and Engagement", description: "Engage your audience with interactive presentations and multimedia experiences.", duration: "18 mins" },
            { title: "Project Showcase and Critique", description: "Perfect your presentation skills and embrace collaboration with peer critique and feedback.", duration: "22 mins" },
            { title: "Optimizing Digital Assets for Various Platforms", description: "Adapt your digital creations for mobile platforms and social media across devices.", duration: "20 mins" },
        ],
    },
    {
        id: "power-of-big-data",
        imageSrc: "/course3.jpg",
        title: "The Power of Big Data",
        byWhom: "purepearl studio",
        rating: "4.5",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Data Science",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer4.png"],
        price: "$45",
        lessons: "14 Lessons",
        duration: "5 hours",
        comments: "59 Comments",
    },
    {
        id: "balancing-productivity-self-care",
        imageSrc: "/course4.jpg",
        title: "Balancing Productivity and Self-Care",
        byWhom: "purepearl studio",
        rating: "4.5",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Productivity",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer4.png"],
        price: "$45",
        lessons: "14 Lessons",
        duration: "5 hours",
        comments: "59 Comments",
    },
    {
        id: "mastering-money-management",
        imageSrc: "/course5.jpg",
        title: "Mastering Money Management",
        byWhom: "purepearl studio",
        rating: "4.5",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Marketing",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer4.png"],
        price: "$45",
        lessons: "14 Lessons",
        duration: "5 hours",
        comments: "59 Comments",
    },
    {
        id: "idea-to-startup-success",
        imageSrc: "/course6.jpg",
        title: "From Idea to Startup Success",
        byWhom: "purepearl studio",
        rating: "4.5",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Creative Marketing",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer4.png"],
        price: "$45",
        lessons: "14 Lessons",
        duration: "5 hours 9 minutes",
        comments: "59 Comments",
    },

    {
        id: "idea-to-startup-success-intermediate",
        imageSrc: "/course1.jpg",
        title: "From Idea to Startup Success",
        byWhom: "purepearl studio",
        rating: "4.5",
        ratingLogo: "/star.png",
        friendly: "Intermediate",
        category: "Web Development",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer4.png"],
        price: "$45",
        lessons: "14 Lessons",
        duration: "12 hours",
        comments: "59 Comments",
    },

    {
        id: "mastering-react-development",
        imageSrc: "/course2.jpg",
        title: "Mastering React Development",
        byWhom: "purepearl studio",
        rating: "4.7",
        ratingLogo: "/star.png",
        friendly: "Intermediate",
        category: "Web Development",
        boughtBy: ["/buyer1.png", "/buyer3.png", "/buyer4.png"],
        price: "$40",
        lessons: "28 Lessons",
        duration: "8 hours",
        comments: "72 Comments",
    },
    {
        id: "complete-brand-design",
        imageSrc: "/course3.jpg",
        title: "Complete Brand Design",
        byWhom: "purepearl studio",
        rating: "4.6",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Graphic Design",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer3.png"],
        price: "$30",
        lessons: "20 Lessons",
        duration: "6 hours",
        comments: "48 Comments",
    },
    {
        id: "mastering-social-media-marketing",
        imageSrc: "/course4.jpg",
        title: "Mastering Social Media Marketing",
        byWhom: "purepearl studio",
        rating: "4.8",
        ratingLogo: "/star.png",
        friendly: "Intermediate",
        category: "Digital Marketing",
        boughtBy: ["/buyer2.png", "/buyer3.png", "/buyer4.png"],
        price: "$38",
        lessons: "26 Lessons",
        duration: "7 hours",
        comments: "81 Comments",
    },
    {
        id: "python-for-data-analysis",
        imageSrc: "/course5.jpg",
        title: "Python for Data Analysis",
        byWhom: "purepearl studio",
        rating: "4.7",
        ratingLogo: "/star.png",
        friendly: "Intermediate",
        category: "Data Science",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer4.png"],
        price: "$50",
        lessons: "32 Lessons",
        duration: "10 hours",
        comments: "67 Comments",
    },
    {
        id: "freelancing-from-scratch",
        imageSrc: "/course6.jpg",
        title: "Freelancing from Scratch",
        byWhom: "purepearl studio",
        rating: "4.5",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Career Development",
        boughtBy: ["/buyer1.png", "/buyer3.png", "/buyer4.png"],
        price: "$25",
        lessons: "18 Lessons",
        duration: "4 hours 30 minutes",
        comments: "54 Comments",
    },

    {
        id: "music-production-fundamentals",
        imageSrc: "/course1.jpg",
        title: "Music Production Fundamentals",
        byWhom: "purepearl studio",
        rating: "4.6",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Music",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer3.png"],
        price: "$30",
        lessons: "22 Lessons",
        duration: "6 hours",
        comments: "47 Comments",
    },
    {
        id: "learn-guitar-from-scratch",
        imageSrc: "/course2.jpg",
        title: "Learn Guitar from Scratch",
        byWhom: "purepearl studio",
        rating: "4.8",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Music",
        boughtBy: ["/buyer1.png", "/buyer3.png", "/buyer4.png"],
        price: "$35",
        lessons: "30 Lessons",
        duration: "8 hours",
        comments: "63 Comments",
    },
    {
        id: "digital-music-composition",
        imageSrc: "/course3.jpg",
        title: "Digital Music Composition",
        byWhom: "purepearl studio",
        rating: "4.5",
        ratingLogo: "/star.png",
        friendly: "Intermediate",
        category: "Music",
        boughtBy: ["/buyer2.png", "/buyer3.png", "/buyer4.png"],
        price: "$42",
        lessons: "26 Lessons",
        duration: "7 hours",
        comments: "51 Comments",
    },
    {
        id: "vocal-training-basics",
        imageSrc: "/course4.jpg",
        title: "Vocal Training Basics",
        byWhom: "purepearl studio",
        rating: "4.7",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Music",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer4.png"],
        price: "$28",
        lessons: "20 Lessons",
        duration: "5 hours",
        comments: "39 Comments",
    },
    {
        id: "advanced-audio-mixing",
        imageSrc: "/course5.jpg",
        title: "Advanced Audio Mixing",
        byWhom: "purepearl studio",
        rating: "4.8",
        ratingLogo: "/star.png",
        friendly: "Advanced",
        category: "Music",
        boughtBy: ["/buyer1.png", "/buyer3.png", "/buyer4.png"],
        price: "$55",
        lessons: "35 Lessons",
        duration: "11 hours",
        comments: "74 Comments",
    },
    {
        id: "songwriting-masterclass",
        imageSrc: "/course6.jpg",
        title: "Songwriting Masterclass",
        byWhom: "purepearl studio",
        rating: "4.6",
        ratingLogo: "/star.png",
        friendly: "Intermediate",
        category: "Music",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer3.png"],
        price: "$45",
        lessons: "24 Lessons",
        duration: "7 hours",
        comments: "58 Comments",
    },

    {
        id: "drawing-fundamentals",
        imageSrc: "/course1.jpg",
        title: "Drawing Fundamentals",
        byWhom: "purepearl studio",
        rating: "4.7",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Drawing & Painting",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer4.png"],
        price: "$25",
        lessons: "18 Lessons",
        duration: "5 hours",
        comments: "42 Comments",
    },
    {
        id: "watercolor-painting-basics",
        imageSrc: "/course2.jpg",
        title: "Watercolor Painting Basics",
        byWhom: "purepearl studio",
        rating: "4.6",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Drawing & Painting",
        boughtBy: ["/buyer2.png", "/buyer3.png", "/buyer4.png"],
        price: "$30",
        lessons: "21 Lessons",
        duration: "6 hours",
        comments: "46 Comments",
    },
    {
        id: "portrait-drawing-mastery",
        imageSrc: "/course3.jpg",
        title: "Portrait Drawing Mastery",
        byWhom: "purepearl studio",
        rating: "4.8",
        ratingLogo: "/star.png",
        friendly: "Intermediate",
        category: "Drawing & Painting",
        boughtBy: ["/buyer1.png", "/buyer3.png", "/buyer4.png"],
        price: "$40",
        lessons: "27 Lessons",
        duration: "8 hours",
        comments: "69 Comments",
    },
    {
        id: "digital-painting-workshop",
        imageSrc: "/course4.jpg",
        title: "Digital Painting Workshop",
        byWhom: "purepearl studio",
        rating: "4.7",
        ratingLogo: "/star.png",
        friendly: "Intermediate",
        category: "Drawing & Painting",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer3.png"],
        price: "$38",
        lessons: "25 Lessons",
        duration: "7 hours",
        comments: "55 Comments",
    },
    {
        id: "character-sketching",
        imageSrc: "/course5.jpg",
        title: "Character Sketching",
        byWhom: "purepearl studio",
        rating: "4.5",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Drawing & Painting",
        boughtBy: ["/buyer2.png", "/buyer3.png", "/buyer4.png"],
        price: "$27",
        lessons: "19 Lessons",
        duration: "5 hours 30 minutes",
        comments: "37 Comments",
    },
    {
        id: "acrylic-painting-masterclass",
        imageSrc: "/course6.jpg",
        title: "Acrylic Painting Masterclass",
        byWhom: "purepearl studio",
        rating: "4.9",
        ratingLogo: "/star.png",
        friendly: "Advanced",
        category: "Drawing & Painting",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer4.png"],
        price: "$48",
        lessons: "31 Lessons",
        duration: "9 hours",
        comments: "71 Comments",
    },

    {
        id: "digital-marketing-fundamentals",
        imageSrc: "/course1.jpg",
        title: "Digital Marketing Fundamentals",
        byWhom: "purepearl studio",
        rating: "4.6",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Marketing",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer3.png"],
        price: "$32",
        lessons: "24 Lessons",
        duration: "6 hours",
        comments: "52 Comments",
    },
    {
        id: "content-marketing-strategy",
        imageSrc: "/course2.jpg",
        title: "Content Marketing Strategy",
        byWhom: "purepearl studio",
        rating: "4.7",
        ratingLogo: "/star.png",
        friendly: "Intermediate",
        category: "Marketing",
        boughtBy: ["/buyer1.png", "/buyer3.png", "/buyer4.png"],
        price: "$40",
        lessons: "28 Lessons",
        duration: "7 hours",
        comments: "61 Comments",
    },
    {
        id: "seo-masterclass",
        imageSrc: "/course3.jpg",
        title: "SEO Masterclass",
        byWhom: "purepearl studio",
        rating: "4.8",
        ratingLogo: "/star.png",
        friendly: "Intermediate",
        category: "Marketing",
        boughtBy: ["/buyer2.png", "/buyer3.png", "/buyer4.png"],
        price: "$45",
        lessons: "30 Lessons",
        duration: "8 hours",
        comments: "76 Comments",
    },
    {
        id: "email-marketing-blueprint",
        imageSrc: "/course4.jpg",
        title: "Email Marketing Blueprint",
        byWhom: "purepearl studio",
        rating: "4.5",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Marketing",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer4.png"],
        price: "$29",
        lessons: "20 Lessons",
        duration: "5 hours",
        comments: "44 Comments",
    },
    {
        id: "marketing-analytics",
        imageSrc: "/course5.jpg",
        title: "Marketing Analytics",
        byWhom: "purepearl studio",
        rating: "4.7",
        ratingLogo: "/star.png",
        friendly: "Intermediate",
        category: "Marketing",
        boughtBy: ["/buyer1.png", "/buyer3.png", "/buyer4.png"],
        price: "$42",
        lessons: "26 Lessons",
        duration: "7 hours 30 minutes",
        comments: "58 Comments",
    },
    {
        id: "brand-marketing-masterclass",
        imageSrc: "/course6.jpg",
        title: "Brand Marketing Masterclass",
        byWhom: "purepearl studio",
        rating: "4.9",
        ratingLogo: "/star.png",
        friendly: "Advanced",
        category: "Marketing",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer3.png"],
        price: "$50",
        lessons: "34 Lessons",
        duration: "10 hours",
        comments: "83 Comments",
    },

    {
        id: "animation-fundamentals",
        imageSrc: "/course1.jpg",
        title: "Animation Fundamentals",
        byWhom: "purepearl studio",
        rating: "4.6",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Animation",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer4.png"],
        price: "$35",
        lessons: "24 Lessons",
        duration: "6 hours",
        comments: "49 Comments",
    },
    {
        id: "2d-character-animation",
        imageSrc: "/course2.jpg",
        title: "2D Character Animation",
        byWhom: "purepearl studio",
        rating: "4.8",
        ratingLogo: "/star.png",
        friendly: "Intermediate",
        category: "Animation",
        boughtBy: ["/buyer1.png", "/buyer3.png", "/buyer4.png"],
        price: "$45",
        lessons: "32 Lessons",
        duration: "9 hours",
        comments: "68 Comments",
    },
    {
        id: "motion-graphics-masterclass",
        imageSrc: "/course3.jpg",
        title: "Motion Graphics Masterclass",
        byWhom: "purepearl studio",
        rating: "4.7",
        ratingLogo: "/star.png",
        friendly: "Intermediate",
        category: "Animation",
        boughtBy: ["/buyer2.png", "/buyer3.png", "/buyer4.png"],
        price: "$48",
        lessons: "29 Lessons",
        duration: "8 hours",
        comments: "63 Comments",
    },
    {
        id: "3d-animation-basics",
        imageSrc: "/course4.jpg",
        title: "3D Animation Basics",
        byWhom: "purepearl studio",
        rating: "4.5",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Animation",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer3.png"],
        price: "$40",
        lessons: "27 Lessons",
        duration: "7 hours",
        comments: "52 Comments",
    },
    {
        id: "animation-storytelling",
        imageSrc: "/course5.jpg",
        title: "Animation Storytelling",
        byWhom: "purepearl studio",
        rating: "4.8",
        ratingLogo: "/star.png",
        friendly: "Intermediate",
        category: "Animation",
        boughtBy: ["/buyer1.png", "/buyer3.png", "/buyer4.png"],
        price: "$38",
        lessons: "23 Lessons",
        duration: "6 hours 30 minutes",
        comments: "57 Comments",
    },
    {
        id: "advanced-animation-techniques",
        imageSrc: "/course6.jpg",
        title: "Advanced Animation Techniques",
        byWhom: "purepearl studio",
        rating: "4.9",
        ratingLogo: "/star.png",
        friendly: "Advanced",
        category: "Animation",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer4.png"],
        price: "$55",
        lessons: "36 Lessons",
        duration: "11 hours",
        comments: "79 Comments",
    },
    {
        id: "piano-playing-for-beginners",
        imageSrc: "/course1.jpg",
        title: "Piano Playing for Beginners",
        byWhom: "purepearl studio",
        rating: "4.7",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Music",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer4.png"],
        price: "$32",
        lessons: "25 Lessons",
        duration: "6 hours 30 minutes",
        comments: "48 Comments",
    },
    {
        id: "music-theory-made-simple",
        imageSrc: "/course2.jpg",
        title: "Music Theory Made Simple",
        byWhom: "purepearl studio",
        rating: "4.6",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Music",
        boughtBy: ["/buyer1.png", "/buyer3.png", "/buyer4.png"],
        price: "$27",
        lessons: "21 Lessons",
        duration: "5 hours",
        comments: "41 Comments",
    },
    {
        id: "professional-music-production",
        imageSrc: "/course3.jpg",
        title: "Professional Music Production",
        byWhom: "purepearl studio",
        rating: "4.9",
        ratingLogo: "/star.png",
        friendly: "Advanced",
        category: "Music",
        boughtBy: ["/buyer2.png", "/buyer3.png", "/buyer4.png"],
        price: "$58",
        lessons: "38 Lessons",
        duration: "12 hours",
        comments: "86 Comments",
    },

    {
        id: "sketching-with-confidence",
        imageSrc: "/course1.jpg",
        title: "Sketching with Confidence",
        byWhom: "purepearl studio",
        rating: "4.7",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Drawing & Painting",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer3.png"],
        price: "$26",
        lessons: "20 Lessons",
        duration: "5 hours 30 minutes",
        comments: "39 Comments",
    },
    {
        id: "landscape-painting-techniques",
        imageSrc: "/course2.jpg",
        title: "Landscape Painting Techniques",
        byWhom: "purepearl studio",
        rating: "4.8",
        ratingLogo: "/star.png",
        friendly: "Intermediate",
        category: "Drawing & Painting",
        boughtBy: ["/buyer1.png", "/buyer3.png", "/buyer4.png"],
        price: "$43",
        lessons: "28 Lessons",
        duration: "8 hours",
        comments: "64 Comments",
    },
    {
        id: "realistic-art-masterclass",
        imageSrc: "/course3.jpg",
        title: "Realistic Art Masterclass",
        byWhom: "purepearl studio",
        rating: "4.9",
        ratingLogo: "/star.png",
        friendly: "Advanced",
        category: "Drawing & Painting",
        boughtBy: ["/buyer2.png", "/buyer3.png", "/buyer4.png"],
        price: "$52",
        lessons: "34 Lessons",
        duration: "10 hours",
        comments: "78 Comments",
    },

    {
        id: "social-media-marketing-basics",
        imageSrc: "/course1.jpg",
        title: "Social Media Marketing Basics",
        byWhom: "purepearl studio",
        rating: "4.6",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Marketing",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer4.png"],
        price: "$30",
        lessons: "22 Lessons",
        duration: "5 hours 30 minutes",
        comments: "47 Comments",
    },
    {
        id: "growth-marketing-strategies",
        imageSrc: "/course2.jpg",
        title: "Growth Marketing Strategies",
        byWhom: "purepearl studio",
        rating: "4.8",
        ratingLogo: "/star.png",
        friendly: "Intermediate",
        category: "Marketing",
        boughtBy: ["/buyer1.png", "/buyer3.png", "/buyer4.png"],
        price: "$44",
        lessons: "29 Lessons",
        duration: "8 hours",
        comments: "67 Comments",
    },
    {
        id: "marketing-campaign-masterclass",
        imageSrc: "/course3.jpg",
        title: "Marketing Campaign Masterclass",
        byWhom: "purepearl studio",
        rating: "4.9",
        ratingLogo: "/star.png",
        friendly: "Advanced",
        category: "Marketing",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer3.png"],
        price: "$55",
        lessons: "36 Lessons",
        duration: "10 hours 30 minutes",
        comments: "82 Comments",
    },

    {
        id: "animation-principles",
        imageSrc: "/course1.jpg",
        title: "The Principles of Animation",
        byWhom: "purepearl studio",
        rating: "4.7",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Animation",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer3.png"],
        price: "$33",
        lessons: "22 Lessons",
        duration: "6 hours",
        comments: "45 Comments",
    },
    {
        id: "cinematic-motion-design",
        imageSrc: "/course2.jpg",
        title: "Cinematic Motion Design",
        byWhom: "purepearl studio",
        rating: "4.8",
        ratingLogo: "/star.png",
        friendly: "Intermediate",
        category: "Animation",
        boughtBy: ["/buyer1.png", "/buyer3.png", "/buyer4.png"],
        price: "$47",
        lessons: "31 Lessons",
        duration: "8 hours 30 minutes",
        comments: "72 Comments",
    },
    {
        id: "professional-3d-animation",
        imageSrc: "/course3.jpg",
        title: "Professional 3D Animation",
        byWhom: "purepearl studio",
        rating: "4.9",
        ratingLogo: "/star.png",
        friendly: "Advanced",
        category: "Animation",
        boughtBy: ["/buyer2.png", "/buyer3.png", "/buyer4.png"],
        price: "$60",
        lessons: "40 Lessons",
        duration: "13 hours",
        comments: "91 Comments",
    },

    // Music
    {
        id: "home-recording-studio",
        imageSrc: "/course4.jpg",
        title: "Home Recording Studio Setup",
        byWhom: "purepearl studio",
        rating: "4.7",
        ratingLogo: "/star.png",
        friendly: "Intermediate",
        category: "Music",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer4.png"],
        price: "$39",
        lessons: "24 Lessons",
        duration: "6 hours 30 minutes",
        comments: "54 Comments",
    },
    {
        id: "electronic-music-production",
        imageSrc: "/course5.jpg",
        title: "Electronic Music Production",
        byWhom: "purepearl studio",
        rating: "4.8",
        ratingLogo: "/star.png",
        friendly: "Intermediate",
        category: "Music",
        boughtBy: ["/buyer1.png", "/buyer3.png", "/buyer4.png"],
        price: "$46",
        lessons: "30 Lessons",
        duration: "8 hours",
        comments: "66 Comments",
    },

    // Drawing & Painting
    {
        id: "ink-drawing-techniques",
        imageSrc: "/course4.jpg",
        title: "Ink Drawing Techniques",
        byWhom: "purepearl studio",
        rating: "4.6",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Drawing & Painting",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer3.png"],
        price: "$29",
        lessons: "19 Lessons",
        duration: "5 hours",
        comments: "43 Comments",
    },
    {
        id: "oil-painting-masterclass",
        imageSrc: "/course5.jpg",
        title: "Oil Painting Masterclass",
        byWhom: "purepearl studio",
        rating: "4.9",
        ratingLogo: "/star.png",
        friendly: "Advanced",
        category: "Drawing & Painting",
        boughtBy: ["/buyer2.png", "/buyer3.png", "/buyer4.png"],
        price: "$54",
        lessons: "33 Lessons",
        duration: "10 hours",
        comments: "75 Comments",
    },

    // Marketing
    {
        id: "influencer-marketing-strategy",
        imageSrc: "/course4.jpg",
        title: "Influencer Marketing Strategy",
        byWhom: "purepearl studio",
        rating: "4.7",
        ratingLogo: "/star.png",
        friendly: "Intermediate",
        category: "Marketing",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer4.png"],
        price: "$36",
        lessons: "23 Lessons",
        duration: "6 hours",
        comments: "49 Comments",
    },
    {
        id: "customer-acquisition-strategies",
        imageSrc: "/course5.jpg",
        title: "Customer Acquisition Strategies",
        byWhom: "purepearl studio",
        rating: "4.8",
        ratingLogo: "/star.png",
        friendly: "Advanced",
        category: "Marketing",
        boughtBy: ["/buyer1.png", "/buyer3.png", "/buyer4.png"],
        price: "$49",
        lessons: "32 Lessons",
        duration: "9 hours",
        comments: "71 Comments",
    },

    // Animation
    {
        id: "stop-motion-animation",
        imageSrc: "/course4.jpg",
        title: "Stop Motion Animation",
        byWhom: "purepearl studio",
        rating: "4.6",
        ratingLogo: "/star.png",
        friendly: "Beginner",
        category: "Animation",
        boughtBy: ["/buyer1.png", "/buyer2.png", "/buyer3.png"],
        price: "$34",
        lessons: "21 Lessons",
        duration: "5 hours 30 minutes",
        comments: "46 Comments",
    },
    {
        id: "character-rigging-and-animation",
        imageSrc: "/course5.jpg",
        title: "Character Rigging and Animation",
        byWhom: "purepearl studio",
        rating: "4.9",
        ratingLogo: "/star.png",
        friendly: "Advanced",
        category: "Animation",
        boughtBy: ["/buyer1.png", "/buyer3.png", "/buyer4.png"],
        price: "$57",
        lessons: "37 Lessons",
        duration: "11 hours",
        comments: "84 Comments",
    },
];